Fix/event announce
jsoxford/hubot pull request #73
Opened 2017-08-16 18:56 UTC by AverageMarcus

2017-08-16 19:36 UTC, danielthepope commented
Even asking "when is the next devops thames valley meetup?" queries DevOps Oxford. More thinking required I'm afraid.

2017-08-16 19:44 UTC, AverageMarcus commented
Feel free to take stab at it. Otherwise I'll see if I get time in the morning. 

Possibly thinking to ignore all those that are out of oxford unless the name matches.

2017-08-17 10:43 UTC, omgmog commented on scripts/new-meetup.js
> +
this change is just white space, right?

2017-08-17 10:46 UTC, AverageMarcus commented on scripts/new-meetup.js
> +
The newline? Yes. I did have a console log in there when debugging.

2017-08-17 10:50 UTC, omgmog requested changes
Looks like it'd work. 

Might want to be more explicit with that return statement so that it makes sense if/when we come back to it in the future? (e.g. `matchingGroups.length > 0` rather than implicit).

2017-08-17 10:52 UTC, AverageMarcus commented
@omgmog Done

2017-08-17 10:53 UTC, omgmog approved these changes

2017-08-17 10:57 UTC, merged